### PR TITLE
Add support of env variables in Ecotone configuration for Symfony

### PR DESCRIPTION
**Pull request by lifinsky**
We can use env variables in Symfony bundle config. Example:
```
ecotone:
  serviceName: "%env(SERVICE_NAME)%"
  defaultErrorChannel: "dbal_dead_letter"

parameters:
  env(SERVICE_NAME): backoffice_service
```

### CODE REVIEW

**Comment by dgafka** [comment]
Cool :) 

Are you able to add some test for this?

**Comment by lifinsky** [comment]
Yes, I will do. Maybe on Thursday.

**Comment by dgafka** [comment]
Sup @lifinsky :)

**Comment by lifinsky** [comment]
Sorry, I remember.

**Comment by dgafka** [comment]
Why closed @lifinsky ?

**Comment by lifinsky** [comment]
It is not possible for int and bool config parameters for example,  because in extension we can not use env variables processors, this is not possible before compile phase https://symfony.com/doc/current/configuration/env_var_processors.html. I have tried in different ways...

**Comment by lifinsky** [comment]
I have tried custom casting before apply to configuration, but also got error on container compile phase, it is not possible remove bundle config parameters after load to bundle configuration, or this needs additional research.

**Pull request closed without merging**
