### PR TITLE
Preparation for Enterprise Licence + Main licence as Apache-2.0

### PR DESCRIPTION
**Pull request by dgafka**
- Change MIT to Apache-2.0 for non Enterprise functionalities, to secure Ecotone trade mark
- Add contribution file
- Add information in composer.json about licensing

### CODE REVIEW

**Comment by lifinsky** [comment]
Hi. Is the current functionality still free? What functionality is planned to be provided under commercial licenses?

**Comment by dgafka** [comment]
@lifinsky yep, all current functionality is still free, this does not change. 
Enterprise functionality will be related to new upcoming features. This PR is preparation for them, as they will have to be licensed separately.

**Comment by lifinsky** [comment]
New projection system, projections without downtime?

**Comment by dgafka** [comment]
> New projection system, projections without downtime?

Can't say much now, as there is still a bit of work to do. But that's on the road map :heart:

**Comment by lifinsky** [comment]
It seems to me that enterprise features should include things like resetting projections without downtime, Kafka support, improved OpenTelemetry support, but leave improvements in the core system similar to those requests that remain in the current feature requests. The framework still needs time to gain a community.

**Comment by dgafka** [comment]
> improved OpenTelemetry support

Can you elaborate more, what you would see there?

**Comment by lifinsky** [comment]
For me, the commercial version is tools for real production where solutions for scaled projection updating, projections resetting without downtime, the ability to use solutions like EventStoreDB for event sourcing, in addition to AMQP Kafka support, possible closer integration with Symfony, the ability to use pessimistic locks during work with aggregates, for example, for an event sourcing aggregates we can use advisory locks or specific retry mechanism for optimistic locks exceptions with a guarantee of getting into the dead-letter queue, a set of automatic metrics for Prometheus, support for columnar databases for projections like ClickHouse.

**Comment by lifinsky** [comment]
OpenTelemetry: show information about related to aggregates queries to projections tables,  db queries related to query bus, called interceptors...

**Pull request merged**
